#This file contains complete CICD 

name: CICD-Pipleine
on:
  workflow_dispatch
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: checking out repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Initializing terraform 
        working-directory: terraformfiles
        run: terraform init

      - name: formating the terraform files
        working-directory: terraformfiles
        run: terraform fmt

      - name: checking terraform file syntax
        working-directory: terraformfiles
        run: terraform validate

      - name: terraform plan and saving plan
        working-directory: terraformfiles
        run: terraform plan -out=tfplan

      - name: terraform apply
        working-directory: terraformfiles
        run: terraform apply -auto-approve

      - name: Upload Terraform Output
        run: |
          terraform output -json > tf_output.json
          aws s3 cp tf_output.json s3://your-terraform-state-bucket/tf_output.json
        
  dynamic-phase:
     runs-on: self-hosted
     needs: CI
     steps:
       - name: checking out repository
         uses: actions/checkout@v4
         
       - name: Download Terraform Output from S3
         run: |
           aws s3 cp s3://cicdbucket2903/tf_output.json terraformfiles/tf_output.json
          
       - name: Generate Ansible Inventory through python
         run: |
           python3 scripts/generate_inventory.py
           
       - name: Upload Inventory as Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ansible-inventory
           path: inventory
  CD:
    runs-on: self-hosted
    needs: [CI,dynamic-phase]
    steps:
      - name: chekcout repository
        uses: actions/checkout@v4
        
      - name: downloading dynamic inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          
      - name: Run Ansible Playbook
        working-directory: ansiblefiles
        run: ansible-playbook -i inventory main.yml


        

        
