#This file contains complete CICD 

name: CICD-Pipleine
on:
  workflow_dispatch
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: checking out repository
        uses: actions/checkout@v4

      - name: Initializing terraform 
        working-directory: terraformfiles
        run: terraform init

      - name: formating the terraform files
        working-directory: terraformfiles
        run: terraform fmt

      - name: checking terraform file syntax
        working-directory: terraformfiles
        run: terraform validate

      - name: terraform plan and saving plan
        working-directory: terraformfiles
        run: terraform plan -out=tfplan

      - name: terraform apply
        working-directory: terraformfiles
        run: terraform apply -auto-approve

      - name: Extract Terraform Output
        working-directory: terraformfiles
        run: terraform output -json > tf_output.json
        
  dynamic-phase:
     runs-on: self-hosted
     needs: CI
     steps:
       - name: checking out repository
         uses: actions/checkout@v4
       - name: Generate Ansible Inventory through python
         run: |
           python3 scripts/generate_inventory.py
       - name: Upload Inventory as Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ansible-inventory
           path: inventory
  CD:
    runs-on: self-hosted
    needs: [CI,dynamic-phase]
    steps:
      - name: chekcout repository
        uses: actions/checkout@v4
        
      - name: downloading dynamic inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          
      - name: Run Ansible Playbook
        working-directory: ansiblefiles
        run: ansible-playbook -i inventory main.yml


        

        
