name: terraform run

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Terraform Init
        working-directory: terraformfiles
        run: terraform init

      - name: Run Terraform Plan
        working-directory: terraformfiles
        env:
          TF_VAR_aws_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform plan

      - name: Run Terraform Apply
        working-directory: terraformfiles
        env:
          TF_VAR_aws_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform apply -auto-approve

        
